services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./db:/app/db
    restart: unless-stopped

  homepage:
    build:
      context: ./homepage
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped